name: Build and Release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Project
      run: make compile-no-venv

    - name: Zip Executable
      run: zip -r myproject.zip ./out/img2pdf.exe

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyProjectExecutable
        path: myproject.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "v1" #${{ github.ref }}
        release_name: ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
        body: "Main executable release"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myproject.zip
        asset_name: project.zip
        asset_content_type: application/zip
